name: Build JOSS Paper

# Dispara quando houver push ou pull request na branch main
on:
  push:
    branches: [ main ]
  pull_request: 
 
jobs:
  build-paper:
    runs-on: ubuntu-latest
    steps:
      # Passo 1: clonar o repositório
      - uses: actions/checkout@v3

      # Passo 2: rodar o Docker do JOSS para compilar o paper
      - name: Build paper with Docker
        run: |
          docker run --rm \
            --volume $PWD/paper:/data \
            --env JOURNAL=joss \
            openjournals/inara

      # Passo 3: salvar o PDF como artefato
      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: paper-pdf
          path: paper/paper.pdf
