name: Build JOSS Paper

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-paper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Install Pandoc and pandoc-citeproc
      - name: Install Pandoc and pandoc-citeproc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc pandoc-citeproc

      - name: Build PDF with Pandoc
        run: pandoc paper.md -o paper.pdf --filter pandoc-citeproc
        working-directory: paper

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: paper-pdf
          path: paper/paper.pdf
