name: Build JOSS Paper

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-paper:
    runs-on: ubuntu-latest
    steps:
      # Passo 1: clonar o repositório
      - uses: actions/checkout@v3

      # Passo 2: instalar tectonic (engine LaTeX) via pip
      - name: Instalar tectonic
        run: |
          python3 -m pip install --upgrade pip
          pip install tectonic

      # Passo 3: gerar PDF com Pandoc (teste local)
      - name: Build PDF with Pandoc
        working-directory: paper
        run: |
          pandoc paper.md \
            --citeproc \
            --pdf-engine=tectonic \
            --resource-path=.. \
            -o paper-pandoc.pdf

      # Passo 4: rodar o Docker do JOSS para compilar o paper oficial
      - name: Build paper with Docker
        run: |
          docker run --rm \
            --volume $PWD/paper:/data \
            --env JOURNAL=joss \
            openjournals/inara

      # Passo 5: salvar os PDFs como artefato
      - name: Upload PDFs
        uses: actions/upload-artifact@v4
        with:
          name: paper-pdfs
          path: |
            paper/paper.pdf
            paper/paper-pandoc.pdf
